#!/bin/bash -ex

# accept github token as input
export GITHUB_TOKEN="$1"
[ -n "$1" ]

while [ 0 ]
do
    echo "running at $(date)"

    CURRENT_VERSION="$(cat VERSION)"
    echo "$RANDOM" > somedata
    # pull up current version for next tests
    perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e' < VERSION > VERSION.tmp
    mv -f VERSION.tmp VERSION

    git add -A
    git commit -m "pulled up"

    git tag ${CURRENT_VERSION}
    git push --tags origin master
    
    # adding this sleep the problem disappears
    sleep 5
    ./gothub -v release --user alanfranz --repo releases-api-test --tag "${CURRENT_VERSION}" --name "${CURRENT_VERSION}"
    ./gothub -v upload --user alanfranz --repo releases-api-test --tag "${CURRENT_VERSION}" --file ./VERSION --name "upload-${CURRENT_VERSION}"
done


