#!/bin/bash

CURRENT_VERSION="$(cat VERSION)"
echo "$RANDOM" > somedata
# pull up current version for next tests
perl -pe 's/^((\d+\.)*)(\d+)(.*)$/$1.($3+1).$4/e' < VERSION > VERSION.tmp
mv -f VERSION.tmp VERSION

git add -A
git commit -m "pulled up"

git tag ${CURRENT_VERSION}
